---
title: "R-packages for dendrochronology"
author:
  - name: Ronald Visser
    orcid: 0000-0001-6966-1729
    email: r.m.visser@saxion.nl
    affiliation: 
      - name: Saxion University of Applied Sciences
        city: Deventer
        country: Netherlands
date: today
bibliography: references.bib
csl: journal-of-computer-applications-in-archaeology.csl
format: html
editor: visual
---

# Dendrochronology and R

This site lists R-packages used in dendrochronology or tree-ring research. For more general information on dendrochronology: [DendroHub](https://www.dendrohub.com/) is an excellent website (maintained by Joe Buck). This overview of R-packages might not be complete, and if you miss anything, please add these using a [pull request in Github](https://github.com/RonaldVisser/Dendro_R/pulls) or contact me.

If you want to start with [R](https://www.r-project.org/), there are several options:

-   [OpenDendro](https://opendendro.org/) is a great resource for those who want to learn about dplR (or dplPy). There are some wonderful tutorials.
-   [Software Carpentry](https://software-carpentry.org/lessons/) is for teaching basic lab skills for research computing and is good for beginners.
-   [Data carpentry](https://datacarpentry.org/lessons/) helps you to gain foundational skills needed to work effectively and reproducibly with data and code.
-   [R for Data Science (2e)](https://r4ds.hadley.nz/) is an extensive and accessible book on general R and doing data science using R.
-   [CTV-Archaeology](https://github.com/benmarwick/ctv-archaeology) is a more general list maintained by Ben Marwick on possibilities and libraries in R, mostly aimed at Archaeology.

I would recommend working with an IDE such as [RStudio](https://posit.co/download/rstudio-desktop/) and always use [projects](https://r4ds.had.co.nz/workflow-projects.html) in your workflow!

# List of R-packages for dendrochronology

+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| ## Package name | ## Description[^1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | ## Links                                                                 | ## Github                                                     |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| BIOdry          | Multilevel ecological data series (MEDS) are sequences of observations ordered according to temporal/spatial hierarchies that are defined by sample designs, with sample variability confined to ecological factors. Dendroclimatic MEDS of tree rings and climate are modeled into normalized fluctuations of tree growth and aridity [@lara2018].                                                                                                                                                                                                                                                                                                                                                                                               | [CRAN](https://cran.r-project.org/web/packages/BIOdry)                   | [GitHub](https://github.com/cran/BIOdry)                      |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| burnr           | Basic tools to analyze forest fire history data (e.g. FHX) in R. This is designed for power users and projects with special needs [@malevich2018].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | [CRAN](https://cran.r-project.org/web/packages/burnr/index.html)         | [GitHub](https://github.com/ltrr-arizona-edu/burnr)           |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](https://ltrr-arizona-edu.github.io/burnr/)                     |                                                               |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dfoliatR        | Tools to identify, quantify, analyze, and visualize growth suppression events in tree rings that are often produced by insect defoliation [@guiterman2020].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [CRAN](https://cran.r-project.org/web/packages/dfoliatR/index.html)      | [Github](https://github.com/chguiterman/dfoliatR/)            |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](https://chguiterman.github.io/dfoliatR/)                       |                                                               |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dendRoAnalyst   | A package to analyse (daily) statistics of dendrometer data, including the daily amplitude of tree growth. Various approaches can be applied to separate radial growth from daily cyclic shrinkage and expansion due to uptake and loss of stem water [@aryal2020].                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [CRAN](https://cran.r-project.org/web/packages/dendRoAnalyst/index.html) | [GitHub](https://github.com/cran/dendRoAnalyst)               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dendroNetwork   | dendroNetwork is a package to create dendrochronological networks for gaining insight into provenance or other patterns based on the statistical relations between tree ring curves. The networks can be used to visualise and understand the relations between tree-ring curves [@visser2024].                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](https://docs.ropensci.org/dendroNetwork/)                      | [GitHub](https://github.com/RonaldVisser/dendroNetwork)       |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dendroSync      | Provides functions for the calculation and plotting of synchrony in tree growth from tree-ring width chronologies (TRW index). It combines variance-covariance (VCOV) mixed modelling with functions that quantify the degree to which the TRW chronologies contain a common temporal signal. It also implements temporal trends in spatial synchrony using a moving window. These methods can also be used with other kind of ecological variables that have temporal autocorrelation corrected [@alday2018].                                                                                                                                                                                                                                    | [CRAN](https://cran.r-project.org/web/packages/DendroSync/index.html)    | [GitHub](https://github.com/cran/DendroSync)                  |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dendroTools     | Provides novel dendroclimatological methods, primarily used by the Tree-ring research community. There are four core functions. The first one is daily_response(), which finds the optimal sequence of days that are related to one or more tree-ring proxy records. Similar function is daily_response_seascorr(), which implements partial correlations in the analysis of daily response functions. For the enthusiast of monthly data, there is monthly_response() function. The last core function is compare_methods(), which effectively compares several linear and nonlinear regression algorithms on the task of climate reconstruction [@jevsenak2018].                                                                                | [CRAN](https://cran.r-project.org/web/packages/dendroTools/index.html)   | [GitHub](https://github.com/jernejjevsenak/dendroTools){.uri} |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| detrendeR       | A Graphical User Interface (GUI) to import, save, detrend and perform standard tree-ring analyses. The interactive detrending allows the user to check how well the detrending curve fits each time-series and change it when needed [@campelo2012].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | [CRAN](https://cran.r-project.org/web/packages/detrendeR/index.html)     | [GitHub](https://github.com/cran/detrendeR){.uri}             |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| dplR            | General package for tree-ring analyses. It is possible to perform tree-ring analyses such as detrending, chronology building, and cross dating. The sotware reads and writes standard file formats used in dendrochronology [@bunn2008; @bunn2010].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [CRAN](https://cran.r-project.org/web/packages/dplR/index.html)          | [GItHub](https://github.com/AndyBunn/dplR){.uri}              |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| fellingdater    | This R-package offers a set of functions that can assist you to infer felling date estimates from dated tree-ring series. The presence of (partially) preserved sapwood or waney edge allows to estimate a range for the actual felling date, for individual series as well as for a group of timbers. Furthermore, an additional function provides a tool to sum sapwood probability distributions, comparable to 'summed probability densities' commonly applied to sets of radiocarbon (^14^C) dates [@haneca2024; @haneca2020].                                                                                                                                                                                                               | [Website](https://docs.ropensci.org/fellingdater/)                       | [GitHub](https://github.com/ropensci/fellingdater/){.uri}     |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| measuRing       | Identification of ring borders on scanned image sections from dendrochronological samples. Processing of image reflectances to produce gray matrices and time series of smoothed gray values. Luminance data is plotted on segmented images for users to perform both: visual identification of ring borders or control of automatic detection. Routines to visually include/exclude ring borders on the R graphical devices, or automatically detect ring borders using a linear detection algorithm. This algorithm detects ring borders according to positive/negative extreme values in the smoothed time-series of gray values. Most of the in-package routines can be recursively implemented using the multiDetect() function [@lara2015]. | [CRAN](https://cran.r-project.org/web/packages/measuRing/index.html)     |                                                               |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| MtreeRing[^2]   | A Shiny Application for Automatic Measurements of Tree-Ring Widths on Digital Images                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | [CRAN](https://cran.r-project.org/web/packages/MtreeRing/index.html)     | [GitHub](https://github.com/ropensci/MtreeRing/){.uri}        |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 | Use morphological image processing and edge detection algorithms to automatically measure tree ring widths on digital images. Users can also manually mark tree rings on species with complex anatomical structures. The arcs of inner-rings and angles of successive inclined ring boundaries are used to correct ring-width series. The package provides a Shiny-based application, allowing R beginners to easily analyze tree ring images and export ring-width series in standard file formats [@shi2019].                                                                                                                                                                                                                                   |                                                                          |                                                               |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| pointRes        | Functions to calculate and plot event and pointer years as well as resilience indices. Designed for dendroecological applications, but also suitable to analyze patterns in other ecological time series [@vandermaaten-theunissen2015].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | [CRAN](https://cran.r-project.org/web/packages/pointRes/index.html)      | [GitHub](https://github.com/cran/pointRes){.uri}              |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| RAPTOR          | Performs wood cell anatomical data analyses on spatially explicit xylem (tracheids) datasets derived from thin sections of woody tissue. The package includes functions for visualisation, detection and alignment of continuous tracheid radial file (defined as rows) and individual tracheid position within an annual ring of coniferous species [@peters2018].                                                                                                                                                                                                                                                                                                                                                                               | [CRAN](https://github.com/the-hull/RAPTOR)                               | [GitHub](https://github.com/the-hull/RAPTOR)                  |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| RingdateR       | RingdateR is a graphical and statistical tool for crossdating annually resolved time series such as tree rings or mollusc, coral and otolith growth increments [@reynolds2021].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](https://ringdater.github.io/ringdater/index.html)              | [GitHub](https://github.com/ringdater/ringdater_pkg){.uri}    |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| SapwoodModel    | This software package fits a model to sapwood data from scots pine (Pinus sylvestris L.) using heartwood data and tree ring width using a nonlinear model. Three models are implemented [@edvardsson2022].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | [Shiny](https://kar26.shinyapps.io/SapwoodModel/)                        | [GitHub](https://github.com/karirogg/SapwoodModel)            |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| tracheideR      | Contains functions to standardize tracheid profiles using the traditional method (Vaganov) and a new method to standardize tracheidograms based on the relative position of tracheids within tree rings [@campelo2016].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | [CRAN](https://cran.r-project.org/web/packages/tracheideR/index.html)    | [GitHub](https://github.com/cran/tracheideR)                  |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| TRADER          | Tree Ring Analysis of Disturbance Events in R (TRADER) package provides only one way for disturbance reconstruction from tree-ring data [@altman2014].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | [CRAN](https://cran.r-project.org/web/packages/TRADER/index.html)        | [GitHub](https://github.com/pavel-fibich/TRADER){.uri}        |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| treeclim        | Bootstrapped response and correlation functions, seasonal correlations and evaluation of reconstruction skills for use in dendroclimatology and dendroecology [@zang2015].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | [CRAN](https://cran.r-project.org/web/packages/treeclim/index.html)      | [GitHub](https://github.com/cszang/treeclim)                  |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| ttprocessing    | For processing the Tree Talker data. It implements the procedures described in the TT+ manual. It allows for converting the raw data into physical quantities and calculating the sap flow from raw temperatures recorded by the probes. It provides some plotting functions and a graphical user interface [@kabala2022; @kabala2024].                                                                                                                                                                                                                                                                                                                                                                                                           |                                                                          | [GitHub](https://github.com/jpkabala96/ttprocessing)          |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| WIAD            | wiad: Wood Image Analysis and Dataset provides a user-friendly interface to digitize wood imagery such as tree ring scans. The package offers a web-based application that the user can run locally from their computers to analyze wood characteristics [@rademacher].                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | [CRAN](https://cran.r-project.org/web/packages/wiad/index.html)          | [GitHub](https://github.com/bnasr/wiad/)                      |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+
| xRing           | Identify and Measure Tree Rings on X-Ray Micro-Density Profiles. This package contains functions to identify tree-ring borders based on X-ray micro-density profiles and a Graphical User Interface (GUI) to visualize density profiles and correct tree-ring borders [@campelo2019].                                                                                                                                                                                                                                                                                                                                                                                                                                                             | [CRAN](https://cran.r-project.org/web/packages/xRing/index.html)         | [GitHub](https://github.com/cran/xRing){.uri}                 |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          |                                                               |
|                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                          | (read only)                                                   |
+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+---------------------------------------------------------------+

[^1]: All descriptions were copied from the website or CRAN archive and edited where needed.

[^2]: There is also ρ-MtreeRing ([GitHub](https://github.com/CambiumRG/rhoMtreeRing)). This is not a R-package, but user-friendly FOSS that streamlines the entire microdensitometry analysis process through a graphical user interface based on Shiny R Software without any programming knowledge. 𝜌-MtreeRing can be personalized and developed by the microdensitometry research community[@garcía-hidalgo2021].

# References
