---
output: github_document
bibliography: references.bib
csl: journal-of-computer-applications-in-archaeology.csl
---

# Dendro_R

A small repository that lists R packages used in dendrochronology or tree-ring research. This overview might not be complete, and if you miss anything, please add these or contact me.

If you want to start with [R](https://www.r-project.org/), there are several options:

-   [OpenDendro](https://opendendro.org/) is a great resource for those who want to learn about dplR or dplPy. There are some wonderful tutorials.
-   [Software Carpentry](https://software-carpentry.org/lessons/) is for teaching basic lab skills for research computing and is good for beginners.
-   [Data carpentry](https://datacarpentry.org/lessons/) helps you to gain foundational skills needed to work effectively and reproducibly with data and code.
-   [R for Data Science (2e)](https://r4ds.hadley.nz/) is an extensive and accessible book on general R and doing data science using R.
-   [CTV-Archaeology](https://github.com/benmarwick/ctv-archaeology) is a more general list maintained by Ben Marwick on possibilities and libraries in R, mostly aimed at Archaeology.

I would recommend working with an IDE such as [RStudio](https://posit.co/download/rstudio-desktop/) and always use [projects](https://r4ds.had.co.nz/workflow-projects.html) in your workflow!

# List of R-packages for dendrochronology

+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| # Package name | # Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Links                                                                | # Github                                                      |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| dfoliatR       | Tools to identify, quantify, analyze, and visualize growth suppression events in tree rings that are often produced by insect defoliation [@guiterman2020]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | [CRAN](https://cran.r-project.org/web/packages/dfoliatR/index.html)    | [Github](https://github.com/chguiterman/dfoliatR/)            |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        |                                                               |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](%3Chttps://chguiterman.github.io/dfoliatR/)                  |                                                               |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| dendroTools    | Provides novel dendroclimatological methods, primarily used by the Tree-ring research community. There are four core functions. The first one is daily_response(), which finds the optimal sequence of days that are related to one or more tree-ring proxy records. Similar function is daily_response_seascorr(), which implements partial correlations in the analysis of daily response functions. For the enthusiast of monthly data, there is monthly_response() function. The last core function is compare_methods(), which effectively compares several linear and nonlinear regression algorithms on the task of climate reconstruction. [@jevsenak2018]                                                                                | [CRAN](https://cran.r-project.org/web/packages/dendroTools/index.html) | [GitHub](https://github.com/jernejjevsenak/dendroTools){.uri} |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| detrendeR      | A Graphical User Interface (GUI) to import, save, detrend and perform standard tree-ring analyses. The interactive detrending allows the user to check how well the detrending curve fits each time-series and change it when needed. [@campelo2012]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | [CRAN](https://cran.r-project.org/web/packages/detrendeR/index.html)   | [GitHub](https://github.com/cran/detrendeR){.uri}             |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        |                                                               |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        | (read only)                                                   |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| dplR           | General package for tree-ring analyses. It is possible to perform tree-ring analyses such as detrending, chronology building, and cross dating. The sotware reads and writes standard file formats used in dendrochronology. [@bunn2008; @bunn2010]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [CRAN](https://cran.r-project.org/web/packages/dplR/index.html)        | [GItHub](https://github.com/AndyBunn/dplR){.uri}              |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| fellingdateR   | This R-package offers a set of functions that can assist you to infer felling date estimates from dated tree-ring series. The presence of (partially) preserved sapwood or waney edge allows to estimate a range for the actual felling date, for individual series as well as for a group of timbers. Furthermore, an additional function provides a tool to sum sapwood probability distributions, comparable to 'summed probability densities' commonly applied to sets of radiocarbon (^14^C) dates.                                                                                                                                                                                                                                          |                                                                        | [GitHub](https://github.com/hanecakr/fellingDateR){.uri}      |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| measuRing      | Identification of ring borders on scanned image sections from dendrochronological samples. Processing of image reflectances to produce gray matrices and time series of smoothed gray values. Luminance data is plotted on segmented images for users to perform both: visual identification of ring borders or control of automatic detection. Routines to visually include/exclude ring borders on the R graphical devices, or automatically detect ring borders using a linear detection algorithm. This algorithm detects ring borders according to positive/negative extreme values in the smoothed time-series of gray values. Most of the in-package routines can be recursively implemented using the multiDetect() function. [@lara2015] | [CRAN](https://cran.r-project.org/web/packages/measuRing/index.html)   |                                                               |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| MtreeRing      | A Shiny Application for Automatic Measurements of Tree-Ring Widths on Digital Images                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | [CRAN](https://cran.r-project.org/web/packages/MtreeRing/index.html)   | [GitHub](https://github.com/ropensci/MtreeRing/){.uri}        |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        |                                                               |
|                | Use morphological image processing and edge detection algorithms to automatically measure tree ring widths on digital images. Users can also manually mark tree rings on species with complex anatomical structures. The arcs of inner-rings and angles of successive inclined ring boundaries are used to correct ring-width series. The package provides a Shiny-based application, allowing R beginners to easily analyze tree ring images and export ring-width series in standard file formats. [@shi2019]                                                                                                                                                                                                                                   |                                                                        |                                                               |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| pointRes       | Functions to calculate and plot event and pointer years as well as resilience indices. Designed for dendroecological applications, but also suitable to analyze patterns in other ecological time series. [@vandermaaten-theunissen2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | [CRAN](https://cran.r-project.org/web/packages/pointRes/index.html)    | [GitHub](https://github.com/cran/pointRes){.uri}              |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        |                                                               |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        | (read only)                                                   |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| RingdateR      | RingdateR is a graphical and statistical tool for crossdating annually resolved time series such as tree rings or mollusc, coral and otolith growth increments. [@reynolds2021]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [Website](https://ringdater.github.io/ringdater/index.html)            | [GitHub](https://github.com/ringdater/ringdater_pkg){.uri}    |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| TRADER         | Tree Ring Analysis of Disturbance Events in R (TRADER) package provides only one way for disturbance reconstruction from tree-ring data. [@altman2014]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | [CRAN](https://cran.r-project.org/web/packages/TRADER/index.html)      | [GitHub](https://github.com/pavel-fibich/TRADER){.uri}        |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+
| xRing          | Identify and Measure Tree Rings on X-Ray Micro-Density Profiles. This package contains functions to identify tree-ring borders based on X-ray micro-density profiles and a Graphical User Interface (GUI) to visualize density profiles and correct tree-ring borders. [@campelo2019]                                                                                                                                                                                                                                                                                                                                                                                                                                                             | [CRAN](https://cran.r-project.org/web/packages/xRing/index.html)       | [GitHub](https://github.com/cran/xRing){.uri}                 |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        |                                                               |
|                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                        | (read only)                                                   |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------+

# References
